### ISSUE TITLE
New DXVK update breaks photoshop for older GPUs

### ISSUE THREAD

**Issue by GasparAM** [MiMillieuh/Photoshop-CC2022-Linux#100]
**Photoshop version**
CC2021

**The problem**
DXVK 2.0 dropped support for a lot of older GPUs like the GeForce GPUs up to the 700 series and the Intel UHD series which are pretty common in laptops. It's almost impossible to understand what the issue is from the logs if you don't know this beforehand since the logs display a generic OpenGL problem error. After using winetricks and installing an older version of DXVK (e.g. v1.10) the program works flawlessly.

**Potential fix**
A potential fix for the problem will be to have the script check if the users GPU supportes the new Vulkan extensions requred by DXVK 2.0 but that would be quite hard. Another possible fix is sticking to v1.10 but we'll be losing potential improvements from the future DXVK versions. Maybe have a warning about the issue in the ReadME and just not bother with it?

**System information**
- Distro : Pop_OS!, Arch Linux
- GPU : Intel UHD 630, GTX 650 Ti
- WINE : 8.0

**Comment by MiMillieuh** [comment]
Hello, thanks for your report,

Since the objective of that repo is to be the most upstream as possible I won't stick with older DXVK. however these GPU you're mentioning are very old (almost 11 years). I'm assuming that someone that want to use such a recent PS version should have some recent hardware.

If using an older DXVK do the tricks well you can do that but I won't lower the DXVK version for everyone because older GPUs doesn't support it especially with the improvement that will come soon.

But mentioning it in the ReadME can be a good idea. but I won't really provide any support about that.

**Comment by wyatt8740** [comment]
This is a bad assumption; just saying. As a 750 Ti owner.

**Comment by GasparAM** [comment]
Please read the issue deacription carefully. The problem arised on Intel UHD 630 which at the time of this issue did not yet have a driver update which added vulkan 1.3 support. Apart from that the NVIDIA 700 series support has been droped with dxvk 2.0 which was mentioned [here](https://github.com/doitsujin/dxvk/wiki/Driver-support#dxvk-next-release).
