### ISSUE TITLE
Cannot change size of window

### ISSUE THREAD

**Issue by DaereanLegrand** [MiMillieuh/Photoshop-CC2022-Linux#29]
First of all thanks for all the work you've done here.

I believe this problem happens because of my tiling window manager, dwm. But it happens that I can resize any other window, even other Wine programs, such as games on steam and others. So I wonder if there is anyway it can get solved. Thanks in advance.

**Comment by MiMillieuh** [comment]
Hello, Well I don't really know why it happens... I can resize on my Gnome Desktop.

Did you tried in another DE ?

**Comment by DaereanLegrand** [comment]
Yes I tried with non-tiling window managers such as openbox and there is no problem, the thing is with tiling window managers such as dwm

**Comment by MiMillieuh** [comment]
maybe it's related to your window manager then...
You could try to disable window decoration in wine
`WINEPREFIX="/path/to/your/install/" winecfg` then go to display and uncheck window decoration.

Maybe it will do the trick. however  I won't add it by default because it's really ugly and not as well integrated with the desktop

**Comment by MiMillieuh** [comment]
I'm closing the issue since I don't have feedback.

You can reopen it if you still encounter the issue
