### ISSUE TITLE
How to add non-English language?

### ISSUE THREAD

**Issue by Lekrixsss** [MiMillieuh/Photoshop-CC2022-Linux#32]
Hi, how can I add non-English language? Photoshop version included in your scripts has only english.

**Comment by MiMillieuh** [comment]
Hi, since it require modification of the adobe PS version I'm unable to tell you about it (Even if my software is supposed to be used with an active subscription. providing some files like these might be illegal... But I'm not a lawyer so I don't really know to be fair... I just want PS to work on Linux and sadly the CC login isn't compatible at all due to IE dependencies ), However, if you tell me what language do you want I can send you the files with the language of your choice.

**Comment by Lekrixsss** [comment]
Ok, send me ukrainian language for photoshop 2021, pls

**Comment by MiMillieuh** [comment]
Hello again,
Here the file you need to put in your photoshop directory :

**This file contains only the ukrainian language**

Steps to follow :

1. Go to your photoshop install dir
2. Go to the `drive_c` then `Program Files` then `Adobe` then `Adobe Photoshop 2021`
3. Remove the `Locales` folder
4. Past the one from the zip I've sent.

[Locales.zip](https://github.com/MiMillieuh/Photoshop-CC2022-Linux/files/8838098/Locales.zip)

I hope it will do the trick on your installation.

Please tell me if it works

Without any answer, I'll close the issue in 3 days

**Comment by Lekrixsss** [comment]
Thx, it's working

**Comment by Lekrixsss** [comment]
Yeah, you can change title

**Comment by MiMillieuh** [comment]
Thanks for your feedback.
