### ISSUE TITLE
[Feature Request] Using CC

### ISSUE THREAD

**Issue by kyngs** [MiMillieuh/Photoshop-CC2022-Linux#79]
**Photoshop version**
CC2021

**System informations**
- Distro : Arch
- GPU : NVIDIA
- WINE version : 7.20

Would it be possible to use the creative cloud on Linux? If I understand correctly, now it is "just" a cracked Photoshop. Considering my school provides the CC subscription, I would love to use it and access the cloud files.

Thanks for your amazing work :+1:

**Comment by MiMillieuh** [comment]
Hello, 

If only I could... I'm in the same situation. 

It's not possible to login with CC that's why it's a "cracked and modified" version that is provided. 

CC login is based on a old Internet explorer framework and it won't run at all on Wine and Linux.

I can't really consider that piracy since Adobe don't support Linux and they don't want to. 

For me that's just a "port" and if something prevent it from working I press "DELETE" on it.

That's sadly included login with CC and that's a shame because I can't use my CC presets.

**Comment by kyngs** [comment]
> Hello, 
> 
> If only I could... I'm in the same situation. 
> 
> It's not possible to login with CC that's why it's a "cracked and modified" version that is provided. 
> 
> CC login is based on a old Internet explorer framework and it won't run at all on Wine and Linux.
> 
> I can't really consider that piracy since Adobe don't support Linux and they don't want to. 
> 
> For me that's just a "port" and if something prevent it from working I press "DELETE" on it.
> 
> That's sadly included login with CC and that's a shame because I can't use my CC presets.

Oh no, I've heard about the internet Explorer debacle a few years ago. However I thought that in year 2022 it would already be gone. Well, it's not. Thanks for your work.
