### ISSUE TITLE
File hoster very slow

### ISSUE THREAD

**Issue by arf20** [MiMillieuh/Photoshop-CC2022-Linux#88]
Using photoshop2021install.sh, the curl download of the PS installer from lulucloud.mywire.org is very slow, at an average of 50KB/s, that's going to be a long time. I got 1000/1000 fiber internet, connection tests ok, and I download torrents at 80MB/s.

I'm in Europe, so maybe the hoster doesn't have servers here?

Just wanted to report this annoyance.
Consider using a better hosting provider, but this is probably non priority.

**Comment by MiMillieuh** [comment]
The file hoster was maybe over high load, it happens often as photoshop is downloaded quite often on my servers.

Since the beginning of the month over 800GB have been downloaded.

That server has a 1000/1000 connection. I usually download at 60 to 80mbps when everything is ok and sometimes at really slow speeds.

Nothing I can really do except buying a new host but usually they are way too overpriced.

**Comment by arf20** [comment]
I understand. Hosting is expensive. So I have mirrored the photoshop installer, available here, if it helps: https://arf20.com/FTPServer/mirror/AdobePhotoshop2021.tar.xz
It might be faster.

**Comment by MiMillieuh** [comment]
> I understand. Hosting is expensive. So I have mirrored the photoshop installer, available here, if it helps: https://arf20.com/FTPServer/mirror/AdobePhotoshop2021.tar.xz
> It might be faster.
> 
> You could have a sort of mirror selection in the script.

That's sweet,

I might update the script when I have some time.

For now you can modify it and replace the url by yours if you want to use it right now.
